---
# This playbook retrieves the default solrconfig.xml

- name: "Retrieve default solrconfig.xml"
  hosts: all
  vars:
    fusion_version: "3.1.3"
    fusion_home: "/opt/lucidworks/fusion/{{ fusion_version }}"
    fusion_user: "fusion"
    fusion_group: "fusion"
  connection: local

  tasks:
  - name: "Retrieve default solrconfig.xml"
    shell: "{{ fusion_home }}/apps/solr-dist/server/scripts/cloud-scripts/zkcli.sh -z localhost:9983 -cmd getfile /lwfusion/3.1.3/solr/configs/default/solrconfig.xml files/default/solrconfig.xml"

